### PR TITLE
Deprecate

### LINKED ISSUE #4935: Merge the compact index client into the Bundler repo
Now that Bundler is already a submodule inside RubyGems, we don't need to keep this shared library in a separate repository anymore.
- [x] move vendored compact index client into Bundler lib #5007
- [ ] update compact index client repository readme
- [ ] push an empty gem with a higher version and a post install message that says the library has moved into Bundler (?)

### PR DESCRIPTION
**Pull request by colby-swandale**
This PR deprecates this library and closes https://github.com/bundler/bundler/issues/4935

\cc @indirect @segiddins

### CODE REVIEW

**Comment by indirect** [comment]
Looks good to me. 👍

**Comment by segiddins** [comment]
Can we remove the travis config so its green?

**Comment by colby-swandale** [comment]
am i right to merge this?

**Comment by indirect** [comment]
@colby-swandale 👍

**Pull request merged**
